Update api-tests.yml

diff --git a/.github/workflows/api-tests.yml b/.github/workflows/api-tests.yml
--- a/.github/workflows/api-tests.yml
+++ b/.github/workflows/api-tests.yml
@@ -21,12 +21,43 @@ jobs:
         with:
           node-version: '20'
 
+      name: Run API Tests
+
+on:
+  push:
+    branches:
+      - main
+
+env:
+  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
+
+jobs:
+  run-api-tests:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '24'
+
       - name: Install Newman
         run: npm install -g newman newman-reporter-html
 
-      - name: Run API tests with environment
-        run:
-          newman run collection.json -e qa-env.json -r cli,html --reporter-html-export report.html
+      - name: List repo files
+        run: ls -la
+
+      - name: Run Newman tests
+        run: |
+          if [[ -f collection.json && -f qa-env.json ]]; then
+            newman run collection.json -e qa-env.json -r cli,html --reporter-html-export report.html
+          else
+            echo "Error: collection.json or qa-env.json not found!"
+            exit 1
+          fi
 
       - name: Upload report
         uses: actions/upload-artifact@v4
